# TAPS
tap "austinjones/taps"
tap "homebrew/bundle"
tap "homebrew/cask"
# tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
# tap "homebrew/cask-versions"
tap "homebrew/core"

# FORMULAE
# brew "clang-format"
# brew "git"
# brew "gmp"
# brew "hugo"
# brew "mysql"
brew "neovim", args: ["HEAD"]
# brew "node"
# brew "pandoc"
# brew "ruby"
brew "rustup-init"
brew "austinjones/taps/tab"

# CASKS
cask "alacritty"
# cask "android-studio"
# cask "discord"
# cask "docker"
cask "firefox"
# cask "flutter"
cask "font-go"
cask "google-backup-and-sync"
cask "itsycal"
cask "rectangle"
cask "spotify"
cask "visual-studio-code"
# cask "wkhtmltopdf"

