tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "neovim" # Text editor
cask "alacritty" # Terminal emulator
cask "itsycal" # macOS system clock replacement
cask "spotify" # Music player
cask "vlc" #Video player
brew "bison"
brew "clang-format"
brew "derby"
brew "flex"
brew "gmp"
brew "go"
brew "node"
brew "pandoc"
brew "python"
brew "r"
brew "unrar"
cask "arduino"
cask "atom"
cask "discord"
cask "font-go"
cask "google-chrome"
cask "google-cloud-sdk"
cask "intellij-idea"
cask "java"
cask "loom"
cask "postman"
cask "processing"
cask "protonvpn"
cask "qlc-plus"
cask "sony-ps4-remote-play"
cask "virtualbox"
cask "wine-stable"
cask "wkhtmltopdf"
cask "xquartz"
