brew "deno"
brew "exercism"
brew "neovim"
brew "node"
brew "typst"
cask "discord"
cask "docker"
cask "firefox"
# cask "flutter"
cask "font-ibm-plex-mono"
cask "font-juliamono"
cask "font-spectral"
cask "google-backup-and-sync"
cask "itsycal"
# cask "loom"
# cask "protonvpn"
cask "rectangle"
cask "spotify"
cask "visual-studio-code"
cask "wezterm"
