[colors]
foreground    = "#ECE1D7"
background    = "#2A2520"
cursor_bg     = "#ECE1D7"
cursor_border = "#ECE1D7"
cursor_fg     = "#2A2520"
selection_bg  = "#4D453E"
selection_fg  = "#ECE1D7"
ansi = ["#352F2A", "#B65C60", "#78997A", "#EBC06D", "#9AACCE", "#B380B0", "#86A3A3", "#A38D78"]
brights = ["#4D453E", "#F17C64", "#99D59D", "#EBC06D", "#9AACCE", "#CE9BCB", "#88B3B2", "#C1A78E"]
